config/routes.rb
Bloccit::Application.routes.draw do

  devise_for :users
  resources :users
  
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index]

  #nested routes
  #resources :topics do
  #resources :posts, except: [:index] do
  #resources :comments, only: [:create, :new, :destroy]
  #resources :favorites, only: [:create, :new, :destroy]
  
  resources :posts, only: [:index]
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
      post '/up-vote', to: 'votes#up_vote', as: :up_vote
      post '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  
  get 'about' => 'welcome#about'
  
  root to: "welcome#index"

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :value, inclusion: { in: [-1, 1], message: "value must be 1 or -1." }
  
  after_save :update_post
  
  def up_vote?
    value == 1
  end
  
  def down_vote?
    value == -1
  end
  
  def create
  end
  
  private
  
  def update_post
   post.update_rank
  end
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  respond_to :html, :js
  before_action :load_post_and_vote
    
  def up_vote
    update_vote(1)
    
    respond_with(@vote) do |format|
      format.html { redirect_to :back }
    end
  end

  def down_vote
    update_vote(-1)
    
    respond_with(@vote) do |format|
      format.html { redirect_to :back }
  
    end
  end

  private
  

  def update_vote(vote_value)
    if (@vote)
      authorize @vote, :update?
      @vote.update(value: vote_value)
    else 
      @vote = @post.votes.build(user_id: current_user.id, value: vote_value)
      authorize @vote, :create?
    end
   end

  def load_post_and_vote
    @post = Post.find(params[:post_id])
    @vote = @post.votes.where(user_id: current_user.id).first 
  end
end

app/views/votes/_points.html.erb
<div class="js-points-summary">
  <h3><div class="js-point-count"><%= pluralize(post.points, 'point')%></div></h3>
  <small>
    <div class="js-up-vote-count"><%= pluralize(post.up_votes, 'up vote') %>,</div>
    <div class="js-down-vote-count"><%= pluralize(post.down_votes, 'down vote') %></div>
  </small>
</div

app/views/votes/_voter.html.erb
<% if policy(Vote.new).create? %>
<%= content_tag :div, class: "pull-left vote-arrows", id: "vote-arrows-#{post.id}" do %>
    <div>
      <%= link_to " ", post_up_vote_path(post), class: up_vote_link_classes(post), method: :post %>
    </div>
    <div>
      <strong><%= post.points %></strong>
    </div>
    <div>
      <%= link_to " ", post_down_vote_path(post), class: down_vote_link_classes(post), method: :post %>
    </div>
<% end %>
<% end %>